#include <pspdisplay.h>
#include <pspkernel.h>
#include <pspctrl.h>
#include <time.h>
#include <pspgu.h>
#include <pspdebug.h>
#include <string.h>
#include <stdio.h>
#include <pspgum.h>
#include "glib2d.h"
#include <psputility.h>
#include <stdlib.h>
#include <math.h>
#include <pspmoduleinfo.h>
#include "save.h"
#include "game_math.h"
#include "game.h"